name: game_tracker
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '3.13.0'

dependencies:
  animated_text_kit: ^4.2.2
  async: ^2.11.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.1.0
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  dio: ^5.5.0+1
  fake_async: ^1.3.1
  flame: ^1.17.0
  flame_rive: ^1.9.1
  flame_riverpod: ^4.0.0+2
  flutter:
    sdk: flutter
  flutter_mock_web_server: ^1.0.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  js: ^0.6.7
  json_annotation: ^4.9.0
  logger: ^2.0.2+1
  mixpanel_flutter: ^2.2.0
  mocktail: ^1.0.3
  overlay_support: ^2.1.0
  path_drawing: ^1.0.0
  phoenix_socket: ^0.7.4
  pointer_interceptor: ^0.10.1
  recase: ^4.1.0
  retrofit: ^4.1.0
  rive: ^0.12.4
  riverpod_annotation: ^2.3.5
  rxdart: ^0.27.7
  sentry_dart_plugin: ^1.0.0
  sentry_flutter: ^7.19.0
  shared_preferences: ^2.0.8
  shimmer: ^3.0.0
  universal_html: ^2.2.4

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  retrofit_generator: '>=7.0.0 <8.0.0'
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/animations/
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
    - family: OpenSansCondensed
      fonts:
        - asset: assets/fonts/OpenSansCondensed-SemiBold.ttf
        - asset: assets/fonts/OpenSansCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSansCondensed-Regular.ttf
        - asset: assets/fonts/OpenSansCondensed-ExtraBold.ttf
    - family: SairaCondensed
      fonts:
        - asset: assets/fonts/SairaCondensed-SemiBold.ttf
        - asset: assets/fonts/SairaCondensed-Medium.ttf
        - asset: assets/fonts/SairaCondensed-Bold.ttf
          weight: 700
